name: Build all crates

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: false
        type: string
        default: "default"
      artifact_name:
        required: false
        type: string
        default: ""

jobs:
  build:
    name: "Build ${{ inputs.target }}"
    runs-on: "${{ inputs.os }}"
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Set $USER if needed
        run: |
          if [ -z "$USER" ]; then
            echo "USER=runner" >> "$GITHUB_ENV"
          fi
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#${{ inputs.target }} -L --accept-flake-config
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact_name != '' }}
        with:
          name: ${{ inputs.artifact_name }}
          path: result/*
