name: CD Check Pipeline

concurrency:
  group: cd-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  merge_group:

  pull_request:
    branches:
      - "release"
      - "release/*"
    types:
      - opened
      - synchronize

jobs:
  build-linux-x86_64:
    name: "Linux x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-x64-4x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-linux-aarch64:
    name: "Linux aarch64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-arm64-8x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
