name: CI Pipeline

concurrency:
  group: pipeline-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  merge_group:

  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize

jobs:
  check:
    name: "Checks"
    uses: ./.github/workflows/ci-check.yml
    with:
      os: warp-ubuntu-latest-x64-4x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-linux-x86_64:
    needs: check
    name: "Linux x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-x64-4x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
